workspace(name = "ci")

load("//bazel:repositories.bzl", "envoy_dependencies")
load("//bazel:cc_configure.bzl", "cc_configure")

# We shouldn't need this, but it's a workaround for https://github.com/bazelbuild/bazel/issues/3580.
local_repository(
    name = "envoy",
    path = "/source",
)

envoy_dependencies(
    path = "@envoy//ci/prebuilt",
)

new_local_repository(
    name = "protobuf_bzl",
    path = "/home/cstrahan/src/envoy/thirdparty/protobuf",
    # We only want protobuf.bzl, so don't support building out of this repo.
    build_file_content = "",
)

cc_configure()

load("@envoy_api//bazel:repositories.bzl", "api_dependencies")
api_dependencies()
